# Generated by Django 5.0.2 on 2024-02-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.CharField(default='visible', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
